name: gen

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ 'go1.16' ]
    name: Go install
    steps:
      - uses: actions/checkout@v2
      - name: Generate Set & Test
        run: |
          go build main.go -o gen && ./gen set -p example NaceSet \*NaceGood -o example/set/nace.gen.go
          go test -v ./example/set/... -race -cover
